### PR TITLE
fix: frames not being filtered on page load

### PR DESCRIPTION
**Pull request by OmgImAlexis**
With this change the checkbox now works correctly on page load.

### CODE REVIEW

**Comment by thetutlage** [comment]
What was not working correctly earlier? It will be great if you can share some context and maybe a before and after screenshot

**Comment by OmgImAlexis** [comment]
@thetutlage the description states the issue? On load the checkbox doesn’t do anything.

**Comment by OmgImAlexis** [comment]
Yes, this fix does in fact fix that. You likely need to clear your browser cache.

You can confirm this by looking at what the code does. It needs this extra call as it's only fired on click otherwise.

**Comment by RomainLanz** [comment]
Well... not building the code will sure not make it work. 😅 
Thanks!

**Review by RomainLanz — APPROVED** [review]

**Comment by OmgImAlexis** [comment]
> Are you using Firefox?

Yes.

**Comment by thetutlage** [comment]
> The issue I see with the checkbox is after checking it when you refresh, it stays checked, but the frame list is not updated according.

@RomainLanz  How can the checkbox stay checked on page refresh? Is this something exclusive to Firefox?

**Comment by RomainLanz** [comment]
> > The issue I see with the checkbox is after checking it when you refresh, it stays checked, but the frame list is not updated according.
> 
> @RomainLanz How can the checkbox stay checked on page refresh? Is this something exclusive to Firefox?

Yes, it is!
Should we add a boolean in the session storage to have the same behavior on other browsers?

**Comment by thetutlage** [comment]
Naah. It's fine, let's stick to the browser behavior

**Comment by OmgImAlexis** [comment]
The checkbox does stay checked/unchecked on refresh btw.

**Pull request merged**
