### PR TITLE
Added: request is optional on youch constructor

### PR DESCRIPTION
**Pull request by Bootta11**
Made request optional in constructor. So now when we render error to HTML there are no exceptions.

### CODE REVIEW

**Comment by thetutlage** [comment]
Can you please share the motivation behind this change?

**Comment by Bootta11** [comment]
Hi,

Sorry for late reply. I'm using your package to create error HTML for sending on mail. Currently there are some errors that are triggered using cron or similar and there is no request. So I made request optional on creating error HTML.

**Comment by thetutlage** [comment]
Okay. So if I get it right. You convert your errors to HTML and then send that HTML in the email, right?

**Comment by NebojsaMoP** [comment]
Yes, you're right.

**Comment by thetutlage** [comment]
You can use the latest version and it will work without request too

**Pull request closed without merging**
