### PR TITLE
chore: add types

### LINKED ISSUE #25: Could not find a declaration file for this module
I try to use youch with typescript, but not find a declaration file (.d.ts). It would be nice to have this file or a @types package.

### PR DESCRIPTION
**Pull request by henry-ns**
Create an `index.d.ts` file for types definition using JSDoc as a reference.

fix #25

### CODE REVIEW

**Comment by henry-ns** [comment]
@RomainLanz, can you take a look, please?

**Comment by thetutlage** [comment]
I suggest not adding private methods to the type declaration. Everything starting with `_` is a private method

**Comment by henry-ns** [comment]
I was thinking about it, but I saw that in JSDOC some had a private tag there, I didn't put it.

I will update with your suggestion.

**Comment by henry-ns** [comment]
done

**Comment by thetutlage** [comment]
Thanks 🙂

**Pull request merged**
