### PR TITLE
Fix `TypeError: Invalid path string` when path is empty in Bun

### PR DESCRIPTION
**Pull request by BSN4**
### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)

### 📚 Description

Bun would throw a `TypeError: Invalid path string: can't be empty` when encountering an empty path. This PR addresses and resolves the issue

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @BSN4! 👋🏻 

Have you considered the possibility that this might be a bug within Bun itself? Given that Bun should ideally be compatible with Node.js when using its API, it seems that the observed behavior doesn't align with this expectation.

Do you happen to have any references or documentation that indicate a different behavior for this API? If not, I would suggest opening an issue in the Bun repository and providing a link to this discussion for context.

**Comment by BSN4** [comment]
Hey @RomainLanz 

I absolutely understand where you're coming from. I agree that Bun seems to have quite a few bugs at the moment. However this particular issue surfaced when one of my dependencies failed to connect to socket. It appears that the path was empty, which led to `youch` being unable to read the file from Bun's source code. I believe this might be due to the fact that Bun doesn't have that `socket` source file.

Given this situation, I still believe that this change is necessary to handle such edge cases. I appreciate your feedback and hope this provides some context on why I proposed this fix.

**Comment by BSN4** [comment]
the optimal solution on Bun's end would be to handle the error if the path is empty. This way, in the event of an empty path, the error will be resolved without causing further complications. Here's a suggested change:

```js
fs.readFile(undefined, 'utf-8', (error, contents) => {
    if (error) {
        resolve(null);
        return;
    }
});
```

**Comment by thetutlage** [comment]
I don't think we should be handling a use case where a property that is supposed to be present all the time is missing in Bun. 

Again, Bun is working towards Node.js compatibility, so instead of all the package authors adding checks for Bun, we should wait for bun for address these issues

**Comment by RomainLanz** [comment]
Fixed in Bun. https://github.com/oven-sh/bun/pull/4693

**Pull request closed without merging**
