### PR TITLE
fix: add `codeContext` property to types

### PR DESCRIPTION
**Pull request by Julien-R44**
Hey ! 
Just this little addition. I need to modify this property elsewhere after creating my Youch instance

### CODE REVIEW

**Comment by thetutlage** [comment]
A couple of things. The `codeContext` doesn't feel like a right name to store "number of lines to display".

Another thing, can we just consume this property internally and only return that many number of lines? For example:

If you say `new Youch({ linesToDisplay: 3 })`, then the Youch JSON and HTML will only return 3 lines at the first place? We might to make modifications here https://github.com/poppinss/youch/blob/develop/src/Youch.js#L115-L118

**Comment by Julien-R44** [comment]
Yes I totally agree. I just didn't want to create a breaking change, but if you're okay with it that's cool !

I'm not sure what you want to change here though: https://github.com/poppinss/youch/blob/ec15f08ba88cd90416acec9511875dae8ee29493/src/Youch.js#L115-L118

at this moment, the stack trace is already "cropped" by `_parseError` : https://github.com/poppinss/youch/blob/ec15f08ba88cd90416acec9511875dae8ee29493/src/Youch.js#L67 

( I didn't really look at how the HTML version worked so sorry if I'm saying something wrong. I'll look more into it tonight. )

**Comment by thetutlage** [comment]
Okay got it. So `codeContext` is already a property which is used internally. So, let's rename this property as we are making it public now.

```ts
options = {
  preLines: 2,
  postLines: 2,
}

new Youch(error, request, options)
```

I see that Youch API can be improved drastically. But for now introducing these two options should do it.

**Comment by thetutlage** [comment]
Looks great 👍

**Comment by thetutlage** [comment]
Released as 3.2.0

**Pull request merged**
