### PR TITLE
Youch Port to Typescript

### PR DESCRIPTION
**Pull request by avidcoder123**
Upon the request on Twitter, I have ported Youch to Typescript.

### CODE REVIEW

**Comment by thetutlage** [comment]
@avidcoder123 Appreciate the efforts here. I am more than happy to accept this PR. But, my plans are to also change the design + the restructure the code a bit. If you follow this task on trello https://trello.com/c/XcVDGZuA/39-rewrite-youch. You can see that I will be changing quite a lot of things.

**Comment by avidcoder123** [comment]
I am aware of the other redesigns, it's just porting Youch to Typescript is just the first step there.

**Comment by avidcoder123** [comment]
Please clarify: is this PR ready to be merged (Youch redesign steps happen one PR at a time) or do you want all the Youch redesigns to be in one PR? Because I doubt I can fully redesign Youch on my own, I'm just doing part of the work here by porting it to TS.

**Comment by avidcoder123** [comment]
Please clarify.

**Comment by thetutlage** [comment]
> Please clarify: is this PR ready to be merged (Youch redesign steps happen one PR at a time) or do you want all the Youch redesigns to be in one PR? Because I doubt I can fully redesign Youch on my own, I'm just doing part of the work here by porting it to TS.

It will change the internals completely as mentioned in the trello card. So even if I merge this PR (which I am happy to), the code will be removed in the next rewrite.

**Comment by avidcoder123** [comment]
Closing PR

**Pull request closed without merging**
